apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`localhost`) && PathPrefix(`{{ required "ERROR You need to specify the URL path where Kibana shall be reachable by --set elasticsearch.kibana.configuration.server.basePath=..." .Values.elasticsearch.kibana.configuration.server.basePath }}`)
    services:
    - kind: Service
      name: {{ .Release.Name }}-kibana
      port: {{ .Values.elasticsearch.kibana.service.ports.http }}
