apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datasciencelab.fullname" . | quote }}
  labels:
    {{- include "datasciencelab.labels" . | nindent 4 }}
  annotations:
    # We need secrets to be fully installed in order to read its random value later
    # see https://helm.sh/docs/topics/charts_hooks/
    # This secret will NOT be uninstalled by helm, you will need to delete it manually!
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  jupyterToken: {{ include "datasciencelab.jupyterToken" . | quote }}
