apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-jupyter
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
