apiVersion: v2
name: datalab-kibana
description: The Eraneos Data Science Lab - Kibana
type: application
version: 1.0.0
appVersion: 8.3.3
keywords:
  - kibana
home: https://www.eraneos.com/
sources:
  - https://github.com/awkgroupag
  - https://github.com/bitnami/charts/tree/master/bitnami/common
  - https://github.com/bitnami/charts/tree/master/bitnami/kibana
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
  - name: kibana
    repository: https://charts.bitnami.com/bitnami
    version: 10.1.20
maintainers:
  - name: Thomas Kathriner
    email: thomas.kathriner@awk.ch
