apiVersion: v1
kind: Service
metadata:
  labels:
    group: controlboard
    project: PROJECT_NAME
    app: PROJECT_NAME
  name: PROJECT_NAME
spec:
  type: ClusterIP
  ports:
  - port: 8888
  selector:
    app: PROJECT_NAME
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    group: controlboard
    project: PROJECT_NAME
    app: PROJECT_NAME
  name: PROJECT_NAME
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - http:
      paths:
      - path: /PROJECT_NAME
        pathType: Prefix
        backend:
          service:
            name: PROJECT_NAME
            port:
              number: 8888
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    group: controlboard
    project: PROJECT_NAME
    app: PROJECT_NAME
  name: PROJECT_NAME
spec:
  containers:
    - image: awkgroupag/controlboard:4106629
      name: controlboard
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
      - name: JUPYTER_ENABLE_LAB
        value: "yes"
      - name: GRANT_SUDO
        value: "yes"
      volumeMounts:
        - name: data-on-laptop
          mountPath: /home/jovyan/data
        - name: work-on-laptop
          mountPath: /home/jovyan/work
        - name: jupyter-config
          mountPath: /home/jovyan/.jupyter/jupyter_notebook_config.py
  volumes:
  - name: data-on-laptop
    hostPath:
      path: DATALAB_DATA_DIR
      type: DirectoryOrCreate
  - name: work-on-laptop
    hostPath:
      path: DATALAB_SOURCECODE_DIR
      type: DirectoryOrCreate
  - name: jupyter-config
    hostPath:
      path: DATALAB_DATA_DIR/PROJECT_NAME.jnc.py
      type: File
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: controlboard-edit-default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/log"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: controlboard-edit
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: controlboard-edit
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: controlboard-read-all-namespaces
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: controlboard-read-all-namespaces
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: controlboard-read-all-namespaces
  apiGroup: rbac.authorization.k8s.io