apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
stringData:
  # See https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration
  CB_SERVER_NAME: {{ .Values.cloudbeaver.conf.server.serverName | quote }}
  CB_SERVER_URL: {{ .Values.cloudbeaver.conf.server.serverURL | quote }}
  CB_ADMIN_NAME: {{ .Values.cloudbeaver.adminUsername | quote }}
  CB_ADMIN_PASSWORD: {{ include "cloudbeaver.adminpassword" . | quote }}
