apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.cloudbeaver.service.port }}
      targetPort: {{ .Values.cloudbeaver.conf.server.serverPort }}
      protocol: {{ .Values.cloudbeaver.service.protocol | quote }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
