apiVersion: v1
kind: Service
metadata:
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME
  name: PROJECT_NAME
spec:
  type: ClusterIP
  ports:
  - port: 8888
  selector:
    app: PROJECT_NAME
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME
  name: PROJECT_NAME
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - http:
      paths:
      - path: /PROJECT_NAME
        pathType: Prefix
        backend:
          service:
            name: PROJECT_NAME
            port:
              number: 8888
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME
  name: PROJECT_NAME
spec:
  containers:
    - image: awkgroupag/datascience-notebook:bc8ee41
      imagePullPolicy: IfNotPresent
      name: awkdatalab
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1000m"
        limits:
          memory: "2048Mi"
          cpu: "2000m"
      env:
      - name: JUPYTER_ENABLE_LAB
        value: "yes"
      - name: GRANT_SUDO
        value: "yes"
      volumeMounts:
        - name: data-on-laptop
          mountPath: /home/jovyan/data
        - name: work-on-laptop
          mountPath: /home/jovyan/work
        - name: jupyter-config
          mountPath: /home/jovyan/.jupyter/jupyter_notebook_config.py
  volumes:
  - name: data-on-laptop
    hostPath:
      path: DATALAB_DATA_DIR
      type: DirectoryOrCreate
  - name: work-on-laptop
    hostPath:
      path: DATALAB_SOURCECODE_DIR
      type: DirectoryOrCreate
  - name: jupyter-config
    hostPath:
      path: DATALAB_DATA_DIR/PROJECT_NAME.jnc.py
      type: File