apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-jupyter
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
