{{- $fullName := include "common.names.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.jupyter.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.jupyter.podLabels "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.jupyter.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.jupyter.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ if .Values.controlboard }}kubernetes-full-namespace-access{{- else }}default{{- end }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.jupyter }}
      securityContext:
      {{- if .sudo }}
        runAsUser: 0
      {{- else }}
        {{- toYaml .securityContext | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          name: {{ .Chart.Name }}
          {{- with .Values.jupyter }}
          image: {{ .image.name }}:{{ .image.tag }}
          resources:
            {{- if $.Values.controlboard }}
            {{- toYaml .containers.resources.controlboard | nindent 12 }}
            {{- else }}
            {{- toYaml .containers.resources.nonControlboard | nindent 12 }}
            {{- end }}
          env:
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: jupyterToken
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            {{- if .sudo }}
            - name: GRANT_SUDO
              value: "yes"
            {{- end }}
            {{- if .containers.extraEnvVars }}
            {{- toYaml .containers.extraEnvVars | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: work
              mountPath: {{ .containers.volumeMounts.mountPath.sourcecode | quote }}
            - name: config-files
              subPath: jupyter_lab_config.py
              mountPath: /home/jovyan/.jupyter/jupyter_lab_config.py
            - name: config-files
              subPath: extensionmanager-extension.jupyterlab-settings
              mountPath: /home/jovyan/.jupyter/lab/user-settings/@jupyterlab/extensionmanager-extension/plugin.jupyterlab-settings
            - name: config-files
              subPath: jupyterlab-lsp.completion.jupyterlab-settings
              mountPath: /home/jovyan/.jupyter/lab/user-settings/@krassowski/jupyterlab-lsp/completion.jupyterlab-settings
            - name: config-files
              subPath: jupyterlab-lsp.plugin.jupyterlab-settings
              mountPath: /home/jovyan/.jupyter/lab/user-settings/@krassowski/jupyterlab-lsp/plugin.jupyterlab-settings
            - name: config-files
              subPath: pycodestyle
              mountPath: /home/jovyan/.config/pycodestyle
            - name: config-files
              subPath: DO-NOT-SAVE-ANYTHING-HERE.md
              mountPath: "/home/jovyan/DO NOT SAVE ANYTHING HERE.md"
            {{- if $.Values.controlboard }}
            - name: config-files
              subPath: jupyterhub_config-CONTROLBOARD.py
              mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/my_config.py
            - name: config-files
              subPath: overrides.json
              mountPath: "/opt/conda/share/jupyter/lab/settings/overrides.json"
            {{- else }}
            - name: config-files
              subPath: jupyterhub_config.py
              mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/my_config.py
            {{- end }}
            - name: data
              mountPath: {{ .containers.volumeMounts.mountPath.data | quote }}
          {{- end }}
      volumes:
      - name: data
        hostPath:
          path: {{ required "You need to set the path for dataDirectory in myvalues.yaml!" .Values.dataDirectory | quote }}
          type: DirectoryOrCreate
      - name: work
        hostPath:
          path: {{ required "You need to set the path for sourcecodeDirectory in myvalues.yaml!" .Values.sourcecodeDirectory | quote }}
          type: DirectoryOrCreate
      - name: config-files
        configMap:
          name: {{ include "common.names.fullname" . }}
