{{- if .Values.controlboard -}}
# In order to be able to use the Python API
# See: https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-full-namespace-access
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["", "apps","extensions", "traefik.containo.us"]
  resources: ["*"]
  verbs: ["*"]
{{ end }}