{{/*
Use a configmap to mount all files in the subdirectory configfiles
All files will be process by helm, replacing {{ XYZ }} appropriately
Do NOT name several files identically!

See https://helm.sh/docs/chart_template_guide/accessing_files/
and https://github.com/helm/helm/issues/4157
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
binaryData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "configfiles/**" }}
    {{- base ($path) | quote | nindent 2 }}: |-
    {{- tpl ($files.Get $path) $ | b64enc | nindent 4 }}
  {{- end }}
