apiVersion: v1
kind: Service
metadata:
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME-neo4j
  name: PROJECT_NAME-neo4j
spec:
  type: NodePort
  ports:
    - port: DATALAB_NEO4J_HTTP_PORT
      targetPort: 7474
      name: http
    - port: DATALAB_NEO4J_BOLT_PORT
      targetPort: 7687
      name: bolt
  selector:
    app: PROJECT_NAME-neo4j
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME-neo4j
  name: PROJECT_NAME-neo4j
spec:
  containers:
    - image: neo4j:4.4.4
      imagePullPolicy: IfNotPresent
      name: neo4j
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
      env:
        - name: NEO4J_AUTH
          value: none
        - name: NEO4J_dbms_security_procedures_unrestricted
          value: apoc.*,gds.*
        - name: NEO4J_dbms_security_procedures_allowlist
          value: apoc.*,gds.*
      volumeMounts:
        - name: neo4j-data-volume
          mountPath: /data
        - name: neo4j-plugins-volume
          mountPath: /plugins
  volumes:
  - name: neo4j-data-volume
    hostPath:
      path: DATALAB_DATA_DIR/PROJECT_NAME-neo4j
      type: Directory
  - name: neo4j-plugins-volume
    hostPath:
      path: DATALAB_SOURCECODE_DIR/datalab-stacks/neo4j/plugins
      type: Directory
