apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: airflow
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`localhost`) && PathPrefix(`/{{ .Release.Namespace }}/airflow`)
    services:
    - kind: Service
      name: {{ if eq .Release.Name "airflow" }}airflow{{ else }}{{ .Release.Name}}-airflow{{ end }}
      port: {{ .Values.airflow.service.ports.http }}
