apiVersion: v1
kind: Service
metadata:
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME-postgres
  name: PROJECT_NAME-postgres
spec:
  type: NodePort
  ports:
    - port: DATALAB_POSTGRES_PORT
      targetPort: 5432
      name: data
  selector:
    app: PROJECT_NAME-postgres
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    group: awkdatalab
    project: PROJECT_NAME
    app: PROJECT_NAME-postgres
  name: PROJECT_NAME-postgres
spec:
  containers:
    - image: postgres:14.2-alpine
      name: postgres
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      ports:
        - containerPort: 5432
          name: data
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
      volumeMounts:
        - name: postgres-volume
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-volume
    hostPath:
      path: DATALAB_DATA_DIR/PROJECT_NAME-postgres
      type: Directory
